name: flutter_libserialport
description: A simple wrapper around libserialport utilizing Flutter's
  build system to build and deploy the C-library for the target platform.
version: 0.3.0
homepage: https://github.com/jpnurmi/flutter_libserialport
repository: https://github.com/jpnurmi/flutter_libserialport
issue_tracker: https://github.com/jpnurmi/flutter_libserialport/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  libserialport:
      git:
        url: https://github.com/ajeeshklr/libserialport.dart.git
        ref: 86780390398d8ddd7f2979d99a7d663f7d8086af

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterLibserialportPlugin
        package: org.sigrok.flutter_libserialport
      linux:
        pluginClass: FlutterLibserialportPlugin
      macos:
        pluginClass: FlutterLibserialportPlugin
      windows:
        pluginClass: FlutterLibserialportPlugin
